<?php
$a=$_POST["a"];
$b=$_POST["b"];
$c=$_POST["c"];
$d=$_POST["d"];
$e=$_POST["e"];
$f=$_POST["f"];
$g=$_POST["g"];
$h=$_POST["h"];
$i=$_POST["i"];
$j=$_POST["j"];
$k=$_POST["k"];
$l=$_POST["l"];
$m=$_POST["m"];
$n=$_POST["n"];
$o=$_POST["o"];
$p=$_POST["p"];
$q=$_POST["q"];
$r=$_POST["r"];
$s=$_POST["s"];
$t=$_POST["t"];
$u=$_POST["u"];
$v=$_POST["v"];
$w=$_POST["w"];
$x=$_POST["x"];
$y=$_POST["y"];
$z=mysqli_connect("localhost","root","","fg");
mysqli_query($z,"insert into attendance values('$a','$b','$c','$d','$e');");
mysqli_query($z,"insert into attendance values('$f','$g','$h','$i','$j');");
mysqli_query($z,"insert into attendance values('$k','$l','$m','$n','$o');");
mysqli_query($z,"insert into attendance values('$p','$q','$r','$s','$t');");
mysqli_query($z,"insert into attendance values('$u','$v','$w','$x','$y');");
echo 'attendance inserted!' ;
?>